### ISSUE TITLE
How to update data use pk

### ISSUE THREAD

**Issue by Jason-Liu-Dream** [at7h/helo#46]
Dear auth,
        I use this library in my program，and like it. But I make a model using auto_pk settings, but when i want to update one row like this:
eg:     await User.update(dict(password=654321, date='2019-01-01'),
                      User.id == user.id)
 It raise ValueError. I found that auto_pk filed id not a type of field type, so   User.id == user.id not work, becasue it not Logic_ or Where_ instance. How can i do this? Is there just define id by self not use auto_pk ?

**Comment by at7h** [comment]
I really appreciate your use and love of trod.

The previous trod is like a grass that has just sprung up. It is a demo with too many problems. During this time I thoroughly restructured it. Trod 0.0.4 is a truly usable version, I hope you still like it, and you are welcome to submit more issues.
